import argparse
import time
import sys
import json
from pathlib import Path
from typing import List, Optional

import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# Force UTF-8 encoding on standard streams to prevent charmap errors on Windows
if sys.platform.startswith('win'):
    try:
        sys.stdout.reconfigure(encoding='utf-8')
        sys.stderr.reconfigure(encoding='utf-8')
    except AttributeError:
        pass

# Ensure project root is in path
ROOT = Path(__file__).parent
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

from env_loader import load_lab_env
from providers import make_provider
from tools import load_tool_declarations, to_openai_tools
from datetime import datetime
from versioning import build_artifact_version, artifact_version_dict
from chat import run_model_tool_loop
from tools.order_lookup.tool import order_lookup
from run_eval import run_evaluation

# Load environment variables
load_lab_env(ROOT)

# Schema definitions matching the expected frontend schema
class ChatMessage(BaseModel):
    role: str = Field(..., description="Role of the sender: 'system', 'user', or 'assistant'")
    content: str = Field(..., description="The textual content of the message")

class ChatRequest(BaseModel):
    messages: List[ChatMessage] = Field(..., description="The conversation history")
    temperature: Optional[float] = Field(0.0, ge=0.0, le=2.0, description="Sampling temperature")
    max_tokens: Optional[int] = Field(None, gt=0, description="Maximum number of tokens to generate")
    session_id: Optional[str] = Field(None, description="The session ID from the frontend to group transcripts")

class ChatResponseUsage(BaseModel):
    prompt_tokens: int = Field(0, description="Number of tokens in the prompt")
    completion_tokens: int = Field(0, description="Number of tokens in the completion")
    total_tokens: int = Field(0, description="Total number of tokens used")

class ChatResponse(BaseModel):
    reply: str = Field(..., description="The response generated by the assistant")
    model: str = Field(..., description="The model name that generated the response")
    usage: ChatResponseUsage = Field(..., description="Token usage details")
    latency_ms: float = Field(..., description="Total processing time in milliseconds")

# Simple token counting helpers
def estimate_tokens(text: str) -> int:
    if not text:
        return 0
    # Rough fallback estimate: ~4 characters per token
    return max(1, len(text) // 4)

# FastAPI App setup
app = FastAPI(
    title="GrabFood Complaint Router Agent Backend",
    description="FastAPI Backend for the GrabFood Complaint Router Agent with Tool Calling.",
    version="1.0.0"
)

# CORS middleware for Next.js frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global variables initialized on startup
PROVIDER_NAME = "openrouter"
VERSION_LABEL = "v1"
MODEL_NAME = None

@app.get("/")
async def root():
    return {
        "status": "online",
        "message": "GrabFood Complaint Router Agent Backend is running."
    }

@app.get("/api/health")
async def health():
    return {
        "status": "healthy",
        "provider": PROVIDER_NAME,
        "version": VERSION_LABEL,
        "model": MODEL_NAME or "default"
    }

# ── Mock Orders API ──────────────────────────────────────────
@app.get("/api/orders")
async def list_orders():
    """Return all mock orders."""
    mock_orders_path = ROOT / "data" / "mock_orders.json"
    if not mock_orders_path.exists():
        return []
    try:
        with open(mock_orders_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Lỗi đọc orders: {str(e)}")

@app.get("/api/orders/{order_id}")
async def get_order_details(order_id: str):
    """Return specific order details by ID."""
    res = order_lookup(order_id)
    if "error" in res:
        raise HTTPException(status_code=404, detail=res["message"])
    return res

# ── Evals API ───────────────────────────────────────────────
@app.post("/api/evals/run")
async def run_evals():
    """Trigger the evaluation suite and return results."""
    try:
        eval_res = run_evaluation(PROVIDER_NAME, MODEL_NAME)
        # Save run log
        runs_dir = ROOT / "runs"
        runs_dir.mkdir(exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%dT%H%M%S")
        run_file = runs_dir / f"eval_{PROVIDER_NAME}_{timestamp}.json"
        
        run_data = {
            "run_id": f"eval_{PROVIDER_NAME}_{timestamp}",
            "provider": PROVIDER_NAME,
            "model": MODEL_NAME,
            "summary": eval_res["summary"],
            "results": eval_res["results"]
        }
        run_file.write_text(json.dumps(run_data, ensure_ascii=False, indent=2), encoding="utf-8")
        
        return run_data
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Lỗi chạy evaluation: {str(e)}")

# ── Log Viewer API ───────────────────────────────────────────
RUNS_DIR = ROOT / "runs"
TRANSCRIPTS_DIR = ROOT / "transcripts"
SAMPLES_RUNS_DIR = ROOT / "samples" / "runs"
SAMPLES_TRANSCRIPTS_DIR = ROOT / "samples" / "transcripts"

@app.get("/api/logs/runs")
async def list_runs():
    """Return summary metadata for every eval-run JSON."""
    items = []
    for d in [RUNS_DIR, SAMPLES_RUNS_DIR]:
        if not d.exists():
            continue
        for f in sorted(d.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True):
            try:
                data = json.loads(f.read_text(encoding="utf-8"))
                items.append({
                    "file": str(f.relative_to(ROOT)),
                    "run_id": data.get("run_id", f.stem),
                    "version": data.get("version"),
                    "artifact_version": data.get("artifact_version"),
                    "suite": data.get("suite", "eval"),
                    "provider": data.get("provider"),
                    "model": data.get("model"),
                    "generated_at": data.get("generated_at", data.get("summary", {}).get("run_at")),
                    "summary": data.get("summary", {}),
                })
            except Exception:
                continue
    return {"runs": items}

@app.get("/api/logs/transcripts")
async def list_transcripts():
    """Return summary metadata for every transcript JSON."""
    items = []
    for d in [TRANSCRIPTS_DIR, SAMPLES_TRANSCRIPTS_DIR]:
        if not d.exists():
            continue
        for f in sorted(d.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True):
            try:
                data = json.loads(f.read_text(encoding="utf-8"))
                items.append({
                    "file": str(f.relative_to(ROOT)),
                    "transcript_id": data.get("transcript_id", f.stem),
                    "version": data.get("version"),
                    "provider": data.get("provider"),
                    "model": data.get("model"),
                    "created_at": data.get("created_at"),
                    "turn_count": len(data.get("turns", [])),
                })
            except Exception:
                continue
    return {"transcripts": items}

@app.get("/api/logs/detail")
async def log_detail(file: str):
    """Return full content of a specific log JSON file (restricted to runs/ transcripts/ samples/)."""
    target = (ROOT / file).resolve()
    # Security: only allow reading inside the project
    if not str(target).startswith(str(ROOT.resolve())):
        raise HTTPException(status_code=403, detail="Access denied")
    if not target.exists():
        raise HTTPException(status_code=404, detail="File not found")
    return json.loads(target.read_text(encoding="utf-8"))

@app.post("/api/chat", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest):
    start_time = time.time()
    
    try:
        # 1. Load prompts and tools dynamically to reflect modifications immediately
        system_prompt_path = ROOT / "artifacts" / "system_prompt.md"
        tools_path = ROOT / "artifacts" / "tools.yaml"
        
        system_prompt = system_prompt_path.read_text(encoding="utf-8")
        tool_declarations = load_tool_declarations(tools_path)
        openai_tools = to_openai_tools(tool_declarations)
        
        # 2. Build provider
        provider = make_provider(PROVIDER_NAME)
        selected_model = MODEL_NAME or getattr(provider, "default_model", None)
        
        # 3. Format history for agent
        formatted_messages = [
            {"role": msg.role, "content": msg.content} 
            for msg in request.messages
        ]
        
        # If system message is not present in formatted_messages, inject it
        has_system = any(m["role"] == "system" for m in formatted_messages)
        if not has_system:
            formatted_messages = [{"role": "system", "content": system_prompt}] + formatted_messages
            
        # 4. Execute the agent tool loop
        result = run_model_tool_loop(
            provider=provider,
            messages=formatted_messages,
            tools=openai_tools,
            model=selected_model,
            max_tool_rounds=4
        )
        reply = result.get("assistant_text", "")
        
        # 5. Measure latency and calculate tokens
        end_time = time.time()
        latency_ms = (end_time - start_time) * 1000
        
        # Build message history string to count tokens
        input_text = " ".join([m.content for m in request.messages])
        prompt_tokens = estimate_tokens(input_text)
        completion_tokens = estimate_tokens(reply)
        total_tokens = prompt_tokens + completion_tokens
        
        # 6. Save transcript if session_id is provided
        if request.session_id:
            try:
                def now_iso() -> str:
                    return datetime.now().isoformat(timespec="seconds")
                
                TRANSCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
                transcript_path = TRANSCRIPTS_DIR / f"web_{request.session_id}.json"
                
                transcript = None
                if transcript_path.exists():
                    try:
                        transcript = json.loads(transcript_path.read_text(encoding="utf-8"))
                    except Exception:
                        pass
                
                if not transcript:
                    artifact_version = build_artifact_version(VERSION_LABEL, system_prompt_path, tools_path)
                    transcript = {
                        "transcript_id": f"web_{request.session_id}",
                        **artifact_version_dict(artifact_version),
                        "provider": PROVIDER_NAME,
                        "model": selected_model or PROVIDER_NAME,
                        "system_prompt": str(system_prompt_path),
                        "tools": str(tools_path),
                        "history_window": 5,
                        "max_tool_rounds": 4,
                        "created_at": now_iso(),
                        "turns": []
                    }
                
                user_text = request.messages[-1].content if request.messages else ""
                turn_index = len(transcript.get("turns", [])) + 1
                
                turn_record = {
                    "turn_index": turn_index,
                    "started_at": now_iso(),
                    "user": user_text,
                    "status": result.get("status", "answered"),
                    "assistant_text": reply,
                    "rounds": result.get("rounds", []),
                    "tool_events": result.get("tool_events", []),
                    "ended_at": now_iso(),
                    "latency_ms": latency_ms,
                    "prompt_tokens": prompt_tokens,
                    "completion_tokens": completion_tokens,
                    "total_tokens": total_tokens
                }
                
                transcript["turns"].append(turn_record)
                transcript["updated_at"] = now_iso()
                
                transcript_path.write_text(json.dumps(transcript, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
                print(f"Saved web transcript to {transcript_path}")
            except Exception as e:
                print(f"Error writing transcript: {e}")
        
        return ChatResponse(
            reply=reply,
            model=selected_model or PROVIDER_NAME,
            usage=ChatResponseUsage(
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=total_tokens
            ),
            latency_ms=latency_ms
        )
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

def main():
    global PROVIDER_NAME, VERSION_LABEL, MODEL_NAME
    
    parser = argparse.ArgumentParser(description="FastAPI Backend for GrabFood Complaint Router.")
    parser.add_argument("--provider", choices=["openrouter", "openai", "anthropic", "gemini"], default="openrouter")
    parser.add_argument("--model", default=None)
    parser.add_argument("--version", default="v1", help="Chosen artifact version label.")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()
    
    PROVIDER_NAME = args.provider
    VERSION_LABEL = args.version
    MODEL_NAME = args.model
    
    print(f"Starting GrabFood Complaint Router Server on port {args.port}...")
    print(f"Provider: {PROVIDER_NAME}, Version: {VERSION_LABEL}, Model: {MODEL_NAME or 'default'}")
    
    uvicorn.run("server:app", host="127.0.0.1", port=args.port, reload=True)

if __name__ == "__main__":
    main()
